namespace EasyTask.Models.Enums
{
    public enum Feature
    {
        // Management Features
        CreateManagement = 1,
        DeleteManagement,
        EditManagement,
        GetManagementByName,
        GetManagementlist,
        ActiveManagement,
        DeactiveManagement,
        BulkDeleteManagement,
        BulkActivateManagement,
        BulkDeActivateManagement,
        GetAllManagements,
        GetProductsByManagementId,
        GetManagementByID,
        GetAllManagement,
        SelectManagementList,
        SelectManagementListByCourseId,
        // Department Features
        EditDepartment = 1000,
        SelectDepartmentList,
        DeleteDepartment,
        ActiveDepartment,
        DeactiveDepartment,
        SelectDepartmentListByManagementIds,
        // Governorate Features
        CreateGovernorate = 2000,
        DeleteGovernorate,
        EditGovernorate,
        GetGovernorateList,
        GetGovernorateByName,
        ActiveGovernorate,
        DeactiveGovernorate,
        AddRangeGovernrates,
        BulkDeleteGovernorate,
        BulkActivateGovernorate,
        BulkDeactivateGovernorate,
        GetAllGovernorateWithAllCities,
        GetGovernorateDropdownList,
        GetGovernoratebyID,
        InitiatGovernratesAndCities,
        // Role Features
        CreateRole = 3000,
        DeleteRole,
        EditRole,
        GetRoleList,
        ActivateRole,
        DeactivateRole,
        AssignFeaturesToRole,
        AssignBulkFeaturesToRole,
        AssignFeaturesToModule,
        AssignModulesToRole,
        UnassignFeaturesfromRole,
        UnassignFeaturesfromModule,
        UnassignBulkFeaturesToRole,
        SearchRoleByName,

        //Candidate Features
        CreateCandidate = 4000,
        GetAllCandidates,
        EditCandidate,
        DeleteCandidate,
        GetCandidateById,
        ExportCandidates,
        SelectCandidateListByDepartmentIds,
        CreateClient,
        EditClient,
        DeleteClient,
        GetClientList,
        SearchClient,
        ActivateClients,
        BulkDeActivateUser,
        DeactivateClients,
        BulkActivateClients,
        BulkDeactivateClients,
        GetClientById,
        GetClientByMobile,
        VerifiedTempClient,
        AddTempClient,
        RejectTempClient,
        VerifiedUser,
        SelectCandidateList,
        EditCandidateLevel,
        GetCandidateData,
        //ResetPasswordOTP,
        //ResetPassword,
        ChangePassword,
        //Login,
        //OTPLogin,
        //VerifyOTP,
        //ResendOTP,
        RecoverAccount,
        GetIDOfDefualtShippingAddress,
        ExportClientsToExcel,
        UserData,
        BulkActivateUser,
        SendEmailToClients,
        GetClientsWithDefualtShippingAddress,
        GetAllPendingClient,
        GetAllNotPendingClient,
        GetTempClientByID,
        RejectUser,
        GetAllVerifiedOrRejectUser,
        GetUserById,
        GetClientDetails,
        GetClientWithPhoneDetails,
        MostUsedGovernorates,
        MostUsedGovernoratesRatio,
        ManagerSelectList,
        EditCandidateBio,
        GetAllCandidatesWithKPIs,
        GetManagerByCandidateId,
        GetAllKPIsByCandidateId,
        EditCandidateAttendanceActivation,
        GetCandidateAttendanceActivation,
        GetEmployeeAttendanceGraph,
        GetAllCandidatesWeeklyStatus,
        // Position Features
        CreatePosition = 5000,
        PositionSelectList,
        EditPosition,
        GetPositionsByName,
        DeletePosition,
        GetPositionById,

        // Media Features
        //UploadMedia ,
        DeleteMedia = 6000,
        DeleteBulkMediaBySourceId,
        AttachMediaToDocument,
        GetAllMediaByDocumentId,
        AttachImageToCandidateDocument,
        //SaveMedia,

        // Document
        AddDocument = 7000,
        GetAllDocuments,

        // General Featueres
        GetFeaturesbyRoleID = 8000,
        GetFeaturesbyModuleID,
        GetFeatueresListed,
        GetModulesbyRoleID,
        //AssignAllFeaturesToRole,
        GetVerifyStatusList,
        GetAllVerifiedStatus,
        CreatePage,
        CreateModule,
        CreateUser,
        EditUser,
        FilterUsers,
        ChangeUserPassword,
        ActivateUser,
        DeactivateUser,
        //CheckOTPValidation
        DashboardStatistics,

        //Level
        AddLevel = 9000,
        LevelHierarchy,
        EditLevel,
        DeleteLevel,
        GetAllLevels,
        GetLevelById,
        SelectLevelList,
        GetNextLevelSequence,
        GetLevelStatistics,
        //Notification
        GetAllNotificationMessages = 10000,
        GetAllNotificationMessagesForClient,

        //Penality
        AddPenality = 11000,
        DeletePenality,
        EditPenality,
        GetAllPenalities,
        GetAllPenalitiesByCandidateId,
        GetPenaltyById,

        //Course
        CreateCourse = 12000,
        DeleteCourse,
        GetAllCourses,
        GetAllCoursesByCandidateId,
        GetCourseById,
        AssignCandidatesToCourse,
        SelectCourseList,
        GetAllCandidatesForCourse,
        UnassignManagmentFromCourse,
        EditCourse,
        UnassignCandidateCourse,
        SetActualStartDate,
        GetCourseStatistics,
        GetAllCoursesWithCandidateNumber,
        //KPI
        AssignKPIToCandidate = 13000,
        UnassignKPIToCandidate,
        //default KPI
        GetAllDefaultKPIs = 14000,
        CreateDefaultKPI,
        DeleteDefaultKPI,

        //Shift
        CreateShift = 15000,
        DeleteShift,
        EditShift,
        AssignCandidateToShift,
        SelectShiftList,
        UnassignCandidateToShift,
        GetAllCandidatesAssignation,
        GetAllShifts,
        GetAllPlannedShiftsByCandidateId,
        GetShiftByID,
        //Attendance
        EditAttendance = 16000,
        GetAllAttendancesForCandidate,
        GetAttendanceCircle,
        GetAllShiftsDetailsForCandidate,
        GetTodayAttendance,
        //PauseShift
        StartPause = 16000,
        StopPause,

        //vacation
        CreateVacation = 17000,
        EditVacation,
        GetAllVacations,
        GetVacationById,
        DeleteVacation,
        VacationsSelectList,
        //VacationRequest
        CreateVacationRequest = 18000,
        GetAllVacationRequests,
        GetCandidateVacationRequests,
        EditVacationRequest,
        RejectVacationRequest,
        FirstApproveVactionRequest,
        GetVacationRequestByID,
        SecondApproveVacationRequest,
        //Permission
        CreatePermission = 19000,
        EditPermission,
        GetPermissionByID,
        PermissionSelectList,
        //PermissionRequest
        CreatePermissionRequest = 20000,
        EditPermissionRequest,
        GetAllPermissionRequests,
        GetAllPermissionRequestsToManager,
        FirstApprovePermissionRequest,
        SecondApprovePermissionRequest,
        RejectPermissionRequest,
        GetPermissionRequestByID,
        CancelPermissionRequest,

        //CandidateVacation
        UpdateCandidateVacationDays = 21000,
        GetAllCandidatesVacations,
        GetCandidateVacationRemainingDays,
        CancelVacationRequest,
        //candidate permission
        GetAllCandidatePermissions = 22000,
        EditPermissionHoursLeftInMonth,

        //SpecialDay
        AddSpecialDay = 23000,
        EditSpecialDay,
        DeleteSpecialDay,
        GetSpecialDayById,
        GetAllSpecialDays,

        //job
        CreateJob = 24000,
        EditJob,
        DeleteJob,
        GetJobById,
        GetAllJobs,
        JobSelectList,

        //Project 
        CreateProject = 25000,
        CreateProjectType,
        EditProject,

        //ExternalMember
        CreateExternalMember = 26000,
        CreateExternalCompany,
        ExternalMemberSelectList,

        //WorkPackage
        CreateWorkPackage = 27000,
        WorkPackageSelectList,

        //Task
        CreateTask = 28000,
        EditTask,
        DeleteTask,
        EditTaskPriority,
    }
}
